### ISSUE TITLE
We need to look at this 

### ISSUE THREAD

**Issue by Chemutaiselim** [devramp/Toast_Snackbar#1]
### The app has a bug

@kibettheophilus look at the .xml file and make sure add the following changes;

- [x] Make sure the classes are all open to allow their use as extensions
- [x] Add sealed classes to reduce the code 
- [x] Make sure you override the functions

**Comment by kibettheophilus** [comment]
@Chemutaiselim make your issues name descriptive,"We need to look at this" isn't the right way.....The ones you listed can be divided into three issues and on each give a detailed desription.

**Comment by Chemutaiselim** [comment]
> @Chemutaiselim make your issues name descriptive,"We need to look at this" isn't the right way.....The ones you listed can be divided into three issues and on each give a detailed desription.

kindly elaborate
